BOARD_TAG    = pro5v328
ARDUINO_PORT = /dev/ttyUSB0

ARDUINO_LIBS = FastLED
LOCAL_CPP_SRCS=$(wildcard *.cpp [!_]*/*.cpp [!_]*/[!_]*/*.cpp)
USER_LIB_PATH=_submodules/arduino-libs
include _submodules/arduino-mk/Arduino.mk

